name: Build

on: [pull_request, push, workflow_dispatch]

jobs:
  carthage:
    name: Carthage
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3.5.0
      - name: Build
        run: xcodebuild clean build -scheme TVShows | xcpretty
        