name: Build

on: [pull_request, push, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3.5.0
      - name: Build
        run: set -euo pipefail; xcodebuild build -scheme TVShows -project 11\ CI/TVShows.xcodeproj -destination 'generic/platform=iOS Simulator' | xcpretty
  tests:
    name: Tests
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3.5.0
      - name: Create sim
        run: xcrun simctl create "iPhone 13 Pro Max" "iPhone 13 Pro Max"
      - name: Tests
        run: |
          set -euo pipefail; 
          xcodebuild test -scheme TVShows -project 11\ CI/TVShows.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 13 Pro Max' | xcpretty
        